# -*- coding:utf-8 -*-

# Max turn.
MAX_TURN = 22

# DIALOGUE STATUS
DIALOGUE_STATUS_FAILED = 0
DIALOGUE_STATUS_SUCCESS = 1
DIALOGUE_STATUS_NOT_COME_YET = -1
DIALOGUE_STATUS_NOT_GET_ALL_SYMPTOMS = -2
DIALOGUE_STATUS_INFORM_WRONG_DISEASE = 2
DIALOGUE_STATUS_INFORM_RIGHT_SYMPTOM = 3


# REWORD FOR DIFFERENT DIALOGUE STATUS.
REWARD_FOR_DIALOGUE_FAILED = - MAX_TURN
REWARD_FOR_DIALOGUE_SUCCESS = 2*MAX_TURN
REWARD_FOR_NOT_GET_ALL_SYMPTOMS = MAX_TURN
REWARD_FOR_NOT_COME_YET = -1
REWARD_FOR_INFORM_WRONG_DISEASE = -MAX_TURN
REWARD_FOR_INFORM_RIGHT_RIGHT_SYMPTOM = 0.1*MAX_TURN

# Special Actions.
CLOSE_DIALOGUE = "closing"
THANKS = "thanks"

# Slot value for unknown, placeholder and no value matches.
VALUE_UNKNOWN = "UNK"
VALUE_PLACEHOLDER = "placeholder"
VALUE_NO_MATCH = "No value matches."

# RESPONSE
I_DO_NOT_CARE = "I don't care."
I_DO_NOT_KNOW = "I don't know."
I_DENY = "No"

# Constraint Check
CONSTRAINT_CHECK_SUCCESS = 1
CONSTRAINT_CHECK_FAILURE = 0

# Update condition
SUCCESS_RATE_THRESHOLD = 0.35
AVERAGE_WRONG_DISEASE = 7